version: '3.8'

services:
  lab-elastic-search:
    container_name: lab-es-container
    image: elasticsearch:8.11.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - lab-es-net
    ports:
      - 9200:9200
  
  lab-kibana:
    container_name: lab-kibana-container
    image: kibana:8.11.1
    environment:
      - ELASTICSEARCH_HOSTS=http://lab-es-container:9200
    networks:
      - lab-es-net
    depends_on:
      - lab-elastic-search
    ports:
      - 5601:5601

networks:
  lab-es-net:
    driver: bridge
